'use strict';
const fullName = 'Blake Lim';
const isCool = true;
const totalPets = 0;
console.log('value of Full Name:', fullName);
console.log('value of Is Cool:', isCool);
console.log('value of Total Pets:', totalPets);
console.log('type of:', typeof fullName);
console.log('type of:', typeof isCool);
console.log('type of:', typeof totalPets);
const unknown = null;
console.log('value of unknown:', unknown);
console.log('type of:', typeof unknown);
let never;
console.log('value of never:', never);
console.log('type of:', typeof never);
