'use strict';
const width = 10;
const height = 10;
const area = width * height;
console.log('value of area:', area);
console.log('type of area:', typeof area);
const bill = 140;
const payment = 135;
const change = bill - payment;
console.log('value of change:', change);
console.log('type of change:', change);
const quizzes = 100;
const midterm = 95;
const final = 90;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('type of grade:', grade);
const firstName = 'Blake';
const lastName = 'Lim';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('type of fullName:', typeof fullName);
const pH = 3;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
const headCount = 7;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('type of motto:', typeof motto);
